---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-configmap
  namespace: team-b
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: apache-team-b
    app.kubernetes.io/version: 2.4.46
data:
  index.html: |
    <h1>Hello World - in team B we run apache!</h1>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: team-b
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: apache-team-b
    app.kubernetes.io/version: 2.4.46
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apache
      app.kubernetes.io/instance: apache-team-b
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache
        app.kubernetes.io/instance: apache-team-b
        app.kubernetes.io/version: 2.4.46
        netic.dk/network-ingress: apache
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.46
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/index.html
            name: apache-conf
            subPath: index.html
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
      volumes:
        - name: apache-conf
          configMap:
            name: apache-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: team-b
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: apache-team-b
    app.kubernetes.io/version: 2.4.46
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: apache-team-b
