---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-configmap
  namespace: team-b
  labels:
    app: apache
data:
  index.html: |
    <h1>Hello World - in team B we run apache!</h1>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: team-b
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 3
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: cntr-httpd
        image: httpd:2.4.46
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/index.html
            name: apache-conf
            subPath: index.html
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
      volumes:
        - name: apache-conf
          configMap:
            name: apache-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: team-b
  labels:
    app: apache
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: apache
