---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: fluxserviceaccount
  annotations:
    description: Requires flux Kustomize and HelmRelease manifests to have serviceAccountName defined
spec:
  crd:
    spec:
      names:
        kind: FluxServiceAccount
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package fluxserviceaccount
        violation[{"msg": msg}] {
          re_match("^(kustomize.toolkit.fluxcd.io|helm.toolkit.fluxcd.io)/", input.review.object.apiVersion)
          re_match("^(Kustomization|HelmRelease)/", input.review.object.kind)
          input.review.object.spec["serviceAccountName"]
          msg := sprintf("Kustomization and HelmRelease must specify serviceAccountName %v/%v", [input.review.object.kind,input.review.object.metadata.name])
        }
