{{- if and (index .Values "helm-operator" "enabled") .Values.global.networkPolicyEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "oaas-namespace.helmop.fullname" . }}
  labels: {{ include "oaas-namespace.helmop.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: helm-operator
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 3030
  egress:
  - {}
{{- end }}
