---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{ include "oaas-namespace.flux.fullname" . }}
  labels: {{ include "oaas-namespace.flux.labels" . | nindent 4 }}
spec:
{{- if .Values.rbac.enabled }}
  serviceAccount: {{ include "oaas-namespace.flux.serviceAccountName" . }}
{{- end }}
  interval: {{ .Values.kustomize.interval }}
  sourceRef:
    kind: GitRepository
    name: {{ include "oaas-namespace.flux.fullname" . }}
  prune: {{ .Values.kustomize.prune }}
  validation: client
  {{- with .Values.kustomize.path }}
  path: {{ . }}
  {{- end }}
