{{- if and .Values.flux.enabled .Values.global.networkPolicyEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "netic.flux.fullname" . }}
  labels: {{ include "netic.flux.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: flux
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 3030
  egress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "netic.flux.fullname" . }}-memcached
  labels: {{ include "netic.flux.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: flux-memcached
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 11211
{{- end }}
