{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oaas-namespace.flux.fullname" . }}
  labels: {{ include "oaas-namespace.flux.labels" . | nindent 4 }}
rules: {{ .Values.rbac.rules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oaas-namespace.flux.fullname" . }}
  labels: {{ include "oaas-namespace.flux.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "oaas-namespace.flux.fullname" . }}
subjects:
  - name: {{ include "oaas-namespace.flux.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end }}
