{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oaas-namespace.flux.serviceAccountName" . }}
  labels: {{ include "oaas-namespace.flux.labels" . | nindent 4 }}
{{- end }}
