contour:
  envoy:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

http_proxies:
  - name: handle-root-context
    namespace: netic-oaas-system
    labels:
      netic.dk/cni.id: root-context-hander
    spec:
      virtualhost:
        fqdn: testing.local
      includes:
        - name: team-a-proxy
          namespace: team-a
          conditions:
            - prefix: /team-a
        - name: team-b-proxy
          namespace: team-b
          conditions:
            - prefix: /team-b
      routes:
        - services:
            - name: kuard
              port: 80
        - conditions:
            - prefix: /oaas-prometheus
          pathRewritePolicy:
            replacePrefix:
              - prefix: /oaas-prometheus
                replacement: /
          services:
            - name: netic-oaas-prometheus
              port: 9090
        - conditions:
            - prefix: /oaas-grafana
          pathRewritePolicy:
            replacePrefix:
              - prefix: /oaas-grafana
                replacement: /
          services:
            - name: netic-oaas-grafana
              port: 80
