---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    customer.dk/owner: customer
    customer.dk/origin: team-b
    customer.dk/type: application-space
    netic.dk/cni.id: team-b-application-x
---
apiVersion: v1
kind: Secret
metadata:
  name: team-b-flux-ssh
  namespace: team-b
type: Opaque
data:
  identity: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUE3T3VoeWdCeENKTWE1UExtQkx1WDgyM2NKTzVnZmNhYzJWVXpKWDNIWUx3UEFJMFJDZXFJCmJSU08rRjZ6MVRZRFA1WDlwVlh2K3NIc2JiOHdHZnNrRmJFNTVvc25mamxHTlFRczNsWXJUeSsvZlBoZW5nWk9pa0dlUFQKbTdFZXlMNGo3dEFDVml5dzlud2hOWWRWWmFPWS96V0M4VHhsZ2lnNG5sSlNDQUZ4L1M4aXlUaW1hSmpwdlVOKzhLcUo4eApBdmw1SmV6dG9MS1o3Q28xOHl5bjgwMXEzL2VIbm9Tdlp5d1ZVNGZsaDZXemNpVmVBbmsyKzdLQ2tDdStVNUVQeEhNRGxpCnUwTTBGd0N5YWJQOU56YndtMmNpMGsrZ2w0SFJWQkpqelRVNWViSkhtUFZrVkFsenJQeitHaEZkWjdrMUJudS8yK2xOY1QKTG04eXhVbWFvZ0RnQ2NjVitNeGlXOEZuVENhMlkwbjFjSTZ2N2lycnZpcEoxTEsrWUpQVFhoQWtMSTFibHlyOSswU0pUKwpmZU00UVN6M3pUZHZMeDFLYmt6bEFNUStpb2M3Y3NnaXNKRXpTd0dTaVJ1c1dJRXdxM3NUZlJVQ3N3WnZBSk9FeUxsNHRJCnFJcC9QRTBnRUxzVUtpSy9UYnM2bjBSaVhibEdPaE1ISGxjT01xUExBQUFGb0lsN2pPYUplNHptQUFBQUIzTnphQzF5YzIKRUFBQUdCQU96cm9jb0FjUWlUR3VUeTVnUzdsL050M0NUdVlIM0duTmxWTXlWOXgyQzhEd0NORVFucWlHMFVqdmhlczlVMgpBeitWL2FWVjcvckI3RzIvTUJuN0pCV3hPZWFMSjM0NVJqVUVMTjVXSzA4dnYzejRYcDRHVG9wQm5qMDV1eEhzaStJKzdRCkFsWXNzUFo4SVRXSFZXV2ptUDgxZ3ZFOFpZSW9PSjVTVWdnQmNmMHZJc2s0cG1pWTZiMURmdkNxaWZNUUw1ZVNYczdhQ3kKbWV3cU5mTXNwL05OYXQvM2g1NkVyMmNzRlZPSDVZZWxzM0lsWGdKNU52dXlncEFydmxPUkQ4UnpBNVlydEROQmNBc21tegovVGMyOEp0bkl0SlBvSmVCMFZRU1k4MDFPWG15UjVqMVpGUUpjNno4L2hvUlhXZTVOUVo3djl2cFRYRXk1dk1zVkptcUlBCjRBbkhGZmpNWWx2Qlowd210bU5KOVhDT3IrNHE2NzRxU2RTeXZtQ1QwMTRRSkN5Tlc1Y3EvZnRFaVUvbjNqT0VFczk4MDMKYnk4ZFNtNU01UURFUG9xSE8zTElJckNSTTBzQmtva2JyRmlCTUt0N0UzMFZBck1HYndDVGhNaTVlTFNLaUtmenhOSUJDNwpGQ29pdjAyN09wOUVZbDI1UmpvVEJ4NVhEaktqeXdBQUFBTUJBQUVBQUFHQVd2elBnTFdVczNkVFg5UU5GSW82L0FrWC83Ckx3cWIwcUphazc0RTBpMGZySFJDM28ra2J4Si9zNlFSYVZ0KzlyWmZNam0yaWFwbEh0aStSZUE4eFllbUE2M1ZoWnpYY1AKaUhMWERIaEpYN3Ixcm5md1ZuNFRrYk5Mb3pYVnF6ZU9MVkIvVW93SkdmVUxveFFzNTd0SElVNHdaWkNHNXFpWWNLMzNxNworRWtkenQ5WVc3RCs3N0t5S2JhUFBMd3lDSUFSMXdNbW1BaFRPeU8ybW1tSUp3NmRhMGtka05ZNHFQbG03dXJjckdFc2RICldESVRuWjJSeVM0d1NGQVVZeUdWRUhKQkxscldURnFGdkhMQWxPK0FUMktZenhiZWhyd2hzZVJJTFhJbjVMVmFOdXRna0UKVEc5allaZDVsY3F3UjM5emFnYWZ0a1ZVNkp1cUZJQ3FSM3RLeGlIYzZPa1VuV3lSWmZiditod3ZvdWVucVRZa2RjNENNZQpnSnppNTNZVklhWjh0c3RIU0d2aXMxVVRTeGxGWjIwS1c0d0VqbzhxZzhrdTJPYTBJUHhrOFg4MjBvWFF4Q0pacFEvZXI2Cjc2TU9IWXlOT28rKytkKzZjRnR5N3NJSnBVdUJ4bGFnb25pT25UT3ltdmp6K2RydEN5dDBRSlpFVmFtUnU1UUgrQkFBQUEKd0ZlWndzU01uVmhmYmg1YnVhYW4wTjZ4ZE5PZjZKWTByZFo5cG9lTFM3dU5SV0FFb1RmR2krMHZrWmRiaVhaVFB5Sks1YQp1emNJb3BDZm9DSXBwOVp2NFZEekMrQ1dJdFhDV2U2RElVU0J4RW1Xbmg5Mlh1bmpKK1M4OC9LM2crZmUvY25ndUtUTzVlCmpZc29Wc0dZckFjaEszRm9ZajRpMk9OWHdFc1dPcTRDMmJBaXN4cmt5NmlVYS9LdGlJeEUzNm5sanZhbE9uazhwL3hBamoKbEFVTDZPQU9vYmRGTTd4RFJwcGMvb2NSVTh0cm44QUZWaUJQSGZ6K3pxVFg1WlRnQUFBTUVBOW44Ym0vVHJKZ3RjcnE4QwpuT0pwaFlFVjVOY0gxeU9rcUJaMmNDeWNQN1NNak8vQnFjTERScXRwMk1CVDdhSFl2VTBpOTB3WnJuSExSU1dyNVcrTUNECmhTcDNLYTlyV2x1VlNoQ1NPNFA3Y2JjYnF5ckszdURJZ3dDUXkvaGIyQXhieG5TamNJTExjRUdEZ3ZTVlhPNHREcXZLVW4Kb2hpSjV3VDFIc0FmeVViNHBZbnhtTm5veXhoaUcvTkVYM1M0NEY1amd6QmRiRGdZYTJJbU1YU3RXYUF2cStucHdLQ2VpTwpwdHRKeFV6V3dyWHIvQ2hVYkZKQ3YycTJHNWpjREJBQUFBd1FEMkRnSmxaZnZEYzRKUE5ZWUd1eFBwWndUM1BoMFVUaldICkpCbG9xcjVPUkhLS3Z6ejdPMDhPVmFZMXdaTzkyb3l2cm5idjE2RnFFRXpBUnRNYjBQWGM0ZGNTcEVLSis0NzhsMkw4bGQKajZLc1pXZmxRVzFTZGNRWDk2NmxJWHZpTzZpWEF6UlJXMXY4QXBzekhCaGJ6Q0lwcmtDbTlSSGplR0Y2YmIzTTdRQzF0RApXNk5rb0dYWDQ5dERjaEZYT3ZGRjVYd0Rna0NGQStoV2VaVE95dzh6YlZqbC9yNXl6SHFBWXVsR0t5bVd5Uld0QldCeTBaCmxDYkxuVGVFL3V1NHNBQUFBclpteDFlR05rTFhOemFDMXJaWGt2Ym1WMGFXTmtheTFyT0hNdGIyRmhjeTF6WTJOa1FHZHAKZEdoMVlnPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: team-b-namespace
  namespace: netic-oaas-system
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/oaas-namespace
      sourceRef:
        kind: GitRepository
        name: k8s-oaas-sccd
        namespace: netic-oaas-system
      interval: 5m
  targetNamespace: team-b
  releaseName: bootstrap-team-b
  values:
    createServiceAccount: true
    networkPolicyEnabled: false
    resourceQuota:
      enabled: false
    rbac:
      enabled: true
      rules:
        # The next is resources directly managed by flux - here only helm releases
        - apiGroups: ["helm.fluxcd.io"]
          resources: ["helmreleases"]
          verbs: ["*"]
        - apiGroups: [""]
          resources: ["services", "configmaps", "secrets"]
          verbs: ["*"]
        - apiGroups: ["apps"]
          resources: ["deployments", "daemonset", "statefulsets"]
          verbs: ["*"]
        - apiGroups: ["projectcontour.io"]
          resources: ["httpproxies"]
          verbs: ["*"]
    git:
      url: ssh://git@github.com/neticdk/k8s-oaas-sccd.git
      ref:
        branch: examples
      secretRef:
        name: team-a-flux-ssh
    kustomize:
      path: secure-namespace-team-b
---
# Allow communication between pods in namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-team-b-pod-to-pod
  namespace: team-b
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: team-b-apache
  namespace: team-b
spec:
  podSelector:
    matchLabels:
      app: apache
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
