{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: compute-defaults
  labels: {{ include "oaas-namespace.labels" . | nindent 4 }}
spec: {{ .Values.limitRange.spec | toYaml | nindent 2 }}
{{- end }}
