{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  labels: {{ include "labels" . | nindent 4 }}
spec: {{ .Values.resourceQuota.spec | toYaml | nindent 2 }}
{{- end }}
