{{- if .Values.pspClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-psp
  labels: {{ include "oaas-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.pspClusterRole }}
subjects:
  - name: "default"
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end }}