---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: netic-oaas-system
spec:
  interval: 5m
  chart:
    spec:
      chart: contour
      version: "2.3.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: netic-oaas-system
      interval: 5m
  targetNamespace: netic-oaas-system
  releaseName: contour
  values:
    envoy:
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
