---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: team-b-proxy
  namespace: team-b
spec:
  routes:
  - services:
    - name: apache-service
      port: 80
    pathRewritePolicy:
      replacePrefix:
        - prefix: /team-b
          replacement: /
    requestHeadersPolicy:
      set:
        - name: Host
          value: apache.local
