---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  namespace: netic-oaas-system
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: kuard-root
    app.kubernetes.io/version: "1"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kuard
                port:
                  number: 80
