---
# Allow communication between pods in namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kuard-ingress
  namespace: netic-oaas-system
spec:
  podSelector:
    matchLabels:
      app: kuard
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
