---
apiVersion: v1
kind: Service
metadata:
  namespace: netic-oaas-system
  labels:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: kuard-root
    app.kubernetes.io/version: "1"
  name: kuard
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: kuard
    app.kubernetes.io/instance: kuard-root
