---
global:
  # -- deploy network policy rules (including default deny rule)
  networkPolicyEnabled: true

# -- resourceQuota specifies quota restrictions for namespace
resourceQuota:
  enabled: true
  spec:
    hard:
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 2Gi

# -- limitRange can be used to set up the default used if a pod does not provide resource limits and requests
limitRange:
  enabled: true
  spec:
    limits:
      - default:
          cpu: 250m
          memory: 512Mi
        defaultRequest:
          cpu: 100m
          memory: 256Mi
        type: Container

# -- networkPolicies defines extra policies for namespace
# E.g., the below policy allowing ingress traffic for port 8080 for any pod/services labelled "netic.dk/network-ingress=default"
# ```
# - name: default-ingress
#   spec:
#    podSelector:
#      matchLabels:
#        netic.dk/network-ingess: default
#    policyTypes:
#    - Ingress
#    ingress:
#      - from:
#        - podSelector: {}
#        ports:
#        - protocol: TCP
#          port: 8080
# ```
networkPolicies: []

# -- pspClusterRole makes a rolebinding for the default service account with the given cluster role setting up the
# default pod security policy for the default service account.
pspClusterRole: ""

# -- createServiceAccount to access the namespace with "edit" permissions (https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)
createServiceAccount: false

# -- enable restrictive access for flux in namespace
rbac:
  enabled: true
  rules:
    - apiGroups: [""]
      resources: ["services", "configmaps", "secrets", "persistentvolumeclaims"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments", "daemonset", "statefulsets"]
      verbs: ["*"]
    - apiGroups: ["batch"]
      resources: ["cronjobs", "jobs"]
      verbs: ["*"]
    - apiGroups: ["extensions", "networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["*"]
    - apiGroups: ["monitoring.coreos.com"]
      resources: ["servicemonitors", "podmonitors", "prometheusrules", "probes"]
      verbs: ["*"]
    - apiGroups: ["projectcontour.io"]
      resources: ["httpproxies"]
      verbs: ["*"]
    - apiGroups: ["policy"]
      resources: ["poddisruptionbudgets"]
      verbs: ["*"]
    - apiGroups: ["helm.toolkit.fluxcd.io"]
      resources: ["helmreleases"]
      verbs: ["*"]
    # allow for "old" Helm Operator based releases for now
    - apiGroups: ["helm.fluxcd.io"]
      resources: ["helmreleases"]
      verbs: ["*"]

# -- configure git source repository
git:
  # -- interval to check for updates
  interval: 2m
  # -- repository url
  url:
  # -- git reference (optional)
  ref:
  # -- reference to secret with git credentials (optional)
  secretRef:

# -- configure the kustomize applied to ns
kustomize:
  # -- reconciliation interval
  interval: 5m
  # -- sub path within git source repo (optional)
  path:
  # -- enables garbage collection
  prune: true

# -- helm-operator installed by subchart (see https://neticdk.github.io/helm-operator)
# This is kept currently to allow a smooth transition from Helm Operator to helm-controller of flux2
helm-operator:
  enabled: true
  helm:
    versions: "v3"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi
  clusterRole:
    create: false
  rbac:
    create: true
    pspEnabled: true
    rules:
      # Allow management of resources which are part of deployments in the namespace
      - apiGroups: [""]
        resources: ["services", "configmaps", "secrets", "persistentvolumeclaims"]
        verbs: ["*"]
      - apiGroups: ["apps"]
        resources: ["deployments", "statefulsets"]
        verbs: ["*"]
      - apiGroups: ["batch"]
        resources: ["cronjobs", "jobs"]
        verbs: ["*"]
      - apiGroups: ["extensions", "networking.k8s.io"]
        resources: ["ingresses"]
        verbs: ["*"]
      - apiGroups: ["monitoring.coreos.com"]
        resources: ["servicemonitors", "podmonitors", "prometheusrules", "probes"]
        verbs: ["*"]
      - apiGroups: ["projectcontour.io"]
        resources: ["httpproxies"]
        verbs: ["*"]
      - apiGroups: ["policy"]
        resources: ["poddisruptionbudgets"]
        verbs: ["*"]
