name: cd

on:
  push:
    branches:
      - main

jobs:
  publish_helm_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install extra tooling
        run: |
          GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs

      - name: Render documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          helm-docs

      #
      # Deploy
      #
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
        with:
          version: v3.5.3

      - name: Add dependency chart repos
        run: |
          helm repo add neticdkhelmop https://neticdk.github.io/helm-operator

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
