name: cd

on:
  push:
    branches:
      - main

jobs:
  publish_helm_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0

      - name: Install extra tooling
        run: |
          GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs

      - name: Render documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          helm-docs

      #
      # Deploy
      #
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1
        with:
          version: v3.5.3

      - name: Add dependency chart repos
        run: |
          helm repo add neticdkhelmop https://neticdk.github.io/helm-operator

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@120944e66390c2534cc1b3c62d7285ba7ff02594 # v1.2.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
