name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - feature/flux2-gotk

jobs:
  charts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0

      - name: Install extra tooling
        run: |
          GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs

      - name: Render documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          helm-docs

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009 # v2.0.1

      - name: Run chart-testing (lint)
        run: ct lint --all --chart-repos neticdkflux=https://neticdk.github.io/flux --chart-repos neticdkhelmop=https://neticdk.github.io/helm-operator
